### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [summer-of-software/vtank#1]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

> A novel effort by [**Add a License Please**](https://github.com/karan/add-a-license-please)

**Comment by pchapin** [comment]
This issue was generated by a program. In fact, the repository does contain a copy of the GPL (so it may be that the program doesn't even work properly). However, it is possible that we haven't tended to all the proper details required to formally apply the GPL to this project. Checking those details is a potential issue for us.

That said, I personally don't appreciate having issues opened by machines. If a human actually cares to have the matter clarified we can address it at that time. Until then I'm closing this issue.

**Comment by karan** [comment]
My bad!
